#!/bin/sh
# Ubuntu にツール類をインストールする。

set -eux

./scripts/install_node_ubuntu
./scripts/install_rust_ubuntu
./scripts/install_delta

cargo install exa -j4
cargo install fd-find -j4
cargo install ripgrep -j4

cargo install editorconfig --git https://github.com/vain0x/editorconfig

: OK
