#!/bin/sh

set -eu

DOTFILES=$(git rev-parse --show-toplevel)

install_bash_config() {
    SRC=$1
    DEST=$2

    test -f "$DEST" || echo "test -r '$SRC' && . '$SRC'" >$DEST
}

install_bash_config "$DOTFILES/config/.bash_aliases" ~/.bash_aliases
install_bash_config "$DOTFILES/config/.profile" ~/.profile

. ~/.profile
