#!/bin/sh

set -eu

DOTFILES=$(git rev-parse --show-toplevel)

install_bash_config() {
    SRC=$1
    DEST=$2

    test -f "$DEST" || echo "test -r '$SRC' && . '$SRC'" >$DEST
}

install_bash_config "$DOTFILES/config/.bashrc" ~/.bashrc
install_bash_config "$DOTFILES/config/.bash_profile" ~/.bash_profile

. ~/.bash_profile
