#!/bin/sh
# [Git](https://git-scm.com/download/linux)

set -eu

DOTFILES=$(git rev-parse --show-toplevel)

# 最新版をインストールし直す。(apt の現在のバージョンだと switch が使えないため。)
sudo apt install -y add-apt-repository software-properties-common
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install -y git

# 設定ファイルを配置する。
ln -sbf $DOTFILES/config/.gitconfig ~/.gitconfig
ln -sbf $DOTFILES/config/.gitignore ~/.gitignore
ln -sbf $DOTFILES/vendor/gitalias/gitalias.txt ~/.gitalias.txt
