#!/bin/sh
# [Install Docker Engine on Ubuntu | Docker Documentation](https://docs.docker.com/engine/install/ubuntu/)
# [Install Docker Compose | Docker Documentation](https://docs.docker.com/compose/install/)

set -eu

# 古いバージョンの Docker をアンインストールする。
sudo apt remove -y docker docker-engine docker.io containerd runc

sudo apt update

sudo apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

# リポジトリを登録する。
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# インストール
sudo apt-get update
sudo apt-get install -y \
    containerd.io \
    docker-ce \
    docker-ce-cli

# Docker-Compose

sudo curl -L "https://github.com/docker/compose/releases/download/1.26.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

mkdir -p ~/bin
sudo ln -sbf /usr/local/bin/docker-compose ~/bin/docker-compose
sudo ln -sbf /usr/local/bin/docker-compose /usr/bin/docker-compose

# Checking

docker --version
docker-compose --version
