#!/bin/sh
# [UbuntuTips/Desktop/InstallFont - Ubuntu Japanese Wiki](https://wiki.ubuntulinux.jp/UbuntuTips/Desktop/InstallFont#A.2BYktS1TBnMKQw8zC5MMgw.2FDDrMFkwiw-)

# <https://github.com/adobe-fonts/source-han-code-jp>

set -eu

if test ! $(which fc-cache)
then
    echo 'WARN: Skip font installation' >&2
    exit
fi

mkdir -p ~/.fonts

curl -L 'https://github.com/adobe-fonts/source-han-code-jp/archive/2.011R.tar.gz' | tar -xz -C ~/.fonts

sudo fc-cache -fv
