#!/bin/sh
# [Git](https://git-scm.com/download/linux)

set -eu

DOTFILES=$(git rev-parse --show-toplevel)

# 最新版をインストールし直す。(apt の現在のバージョンだと switch が使えないため。)
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install -y git

mkdir -f "$HOME/.config/git"

# 設定ファイルを配置する。
if test ! -f "$HOME/.config/git/config"
then
    cat >"$HOME/.config/git/config" <<END
[include]
    path = "$DOTFILES/vendor/gitalias/gitalias.txt"
    path = "$DOTFILES/config/git/config"

[core]
    excludesfile = "$DOTFILES/config/git/ignore"
END
fi
