#!/bin/sh
# [UbuntuTips/Desktop/InstallFont - Ubuntu Japanese Wiki](https://wiki.ubuntulinux.jp/UbuntuTips/Desktop/InstallFont#A.2BYktS1TBnMKQw8zC5MMgw.2FDDrMFkwiw-)

# <https://github.com/JetBrains/JetBrainsMono>

set -eu

JETBRAINS_MONO_URI='https://github.com/JetBrains/JetBrainsMono/releases/download/v2.001/JetBrains.Mono.2.001.zip'

if test ! $(which fc-cache)
then
    echo 'WARN: Skip font installation' >&2
    exit
fi

mkdir -p ~/.fonts

if test ! -d ~/.fonts/jet-brains-mono
then
    curl -sL "$JETBRAINS_MONO_URI" -o /tmp/jet-brains-mono.zip
    unzip -q /tmp/jet-brains-mono.zip -d ~/.fonts
fi

sudo fc-cache -fv
