#!/bin/sh
# [Git](https://git-scm.com/download/linux)

set -eu

DOTFILES=$(git rev-parse --show-toplevel)

# 最新版をインストールし直す。(apt の現在のバージョンだと switch が使えないため。)
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install -y git

# 設定ファイルを配置する。
if test ! -f ~/.gitconfig
then
    cat >~/.gitconfig <<END
[include]
    path = "$DOTFILES/vendor/gitalias/gitalias.txt"
    path = "$DOTFILES/config/.gitconfig"

[core]
    excludesfile = "$DOTFILES/config/.gitignore"
END
fi
